### ISSUE TITLE
xpath to obtain next editorial page on "get_next_edlist" not finding "Pagina Sigiente"

### ISSUE THREAD

**Issue by jprisab** [rinze/el_pais_editoriales#1]
Problem seen in elpais_spyder.py

I have tried executing the code and I get the problem that in the function 
get_next_edlist(tree)

the XPATH expresion
next_edlist = tree.xpath(u'//a[@title="' + "Página siguiente".decode("utf8") + '"]/@href') 
does not return any result and therefore it is failing afterwards

I guess the format of the page has changed.

Workarounded it in my code by substituting:

    next_edlist = tree.xpath(u'//a[@title="' + "Página siguiente".decode("utf8") + '"]/@href')
    next_edlist = "http://www.elpais.com" + next_edlist[0]

by:
     next_edlist = tree.xpath('//li[@class="paginacion-siguiente"]/a[1]/@href')[0]

**Comment by rinze** [comment]
It is possible that the page tags have changed since I wrote this code. The same for the other issue you opened.
