### ISSUE TITLE
elpais_spider.py : Fucntion get_edarticles not finding elemets for artlist

### ISSUE THREAD

**Issue by jprisab** [rinze/el_pais_editoriales#2]
Problem seen in elpais_spyder.py

I have tried executing the code and I get the problem that in the function
get_edarticles(tree)

the XPATH expresion
artlist = tree.xpath('//div[@class="columna_principal"]//h2/a[@title="Ver noticia"]/@href')

returns  NO result 

I guess the format of the page has changed.

Workarounded it in my code by substitutingit by:

    artlist = tree.xpath('//h2[@class="articulo-titulo" and @itemprop="headline"]/a[1]/@href')

**Comment by rinze** [comment]
See my answer to #1
