### ISSUE TITLE
¿Donde se genera y guarda counts.Rda?

### ISSUE THREAD

**Issue by s-nt-s** [rinze/el_pais_editoriales#5]
Hola

Creo entender que `analyze.R` debería generar un `counts.Rda` que luego se usa en `generate_vis.R` y en la aplicación `shiny` pero parece faltar justo esa parte que salva el fichero.

Buscando por internet creo que seria algo como `save(counts, file="counts.Rda")` pero me extraña que algo así falte en el código, ¿puede ser otro el error? ¿puede ser que en el repositorio no este la última versión del proyecto?

**Comment by rinze** [comment]
Pues no lo recuerdo, honestamente, pero veo que lo incluí en el repositorio, así que yo miraría los nombres de las variables que salen de ahí y las que se generan en el código para guardar una versión actualizada.
